### ISSUE TITLE
Tea Cozy (BWS)

### ISSUE THREAD

**Issue by asadmehdi785** [bishthetiger/prj-rev-bwfs-tea-cozy#1]
### Criteria 1: HTML Structure  
* _Score Level:_ 4
* _Comment(s):_ HTML implementation enables proper use of flexbox. HTML structure reflects the grouping and flow of content in the web browser.
 
### Criteria 2: Visual Layout
* _Score Level:_ 3
* _Comment(s):_ Layout matches the design spec in all sections except for the header.
 
### Criteria 3: Use of Flexbox
* _Score Level:_ 4
* _Comment(s):_ Flexbox properties are correctly applied to flex containers and flex items throughout. Flexbox is used properly and is the primary way of positioning.

### Criteria 4: Implementation of Design Specification and Content
* _Score Level:_ 2
* _Comment(s):_ There are style omissions from the design specification in many sections of the page (missing Helvetica font-family).
 
### Overall Score: 13/16
Great work overall! There were just a few things that I wanted to address. Firstly, we would want the header at the top to be stickied to the top of the viewport. That is, when we scroll down the page, it should stick right at the top, leaving no gap. It looks like the header on your page leaves a bit of a gap. Also, I noticed that the Helvetica font was not being applied correctly on the page. The reason for this is because of this line in the CSS:

https://github.com/bishthetiger/prj-rev-bwfs-tea-cozy/blob/f7686866a7fe5b88b93e05ee2fe7ca0fe8f9dde4/TeaCozy/resources/css/style.css#L2

We will need to put a comma in between the fonts here, or else the browser will try to treat them as one font and it'll give an error. In fact, if we were to look at Chrome Developer Tools, we would see this:

![invalid_css](https://user-images.githubusercontent.com/16052289/48986476-7cfd0800-f0e3-11e8-9bc9-bcb90f415627.png)

So it seems to be treating ""Helvetica" sans-serif" as one font and it gets confused, so it just defaults to another font. We can fix this by putting a comma in between the two fonts:

```
font-family: "Helvetica", sans-serif;
```

And then it will work properly.

Good job overall! I hope you enjoy the rest of the course!

**Comment by bishthetiger** [comment]
Great - thank you. Noted on the omission of the comma between fonts.
